force-app/main/default/objects/TriggerDispatch__mdt/TriggerDispatch__mdt.object-meta.xml
<CustomObject>
    <description>Trigger Dispatcher</description>
    <label>TriggerDispatch</label>
    <pluralLabel>TriggerDispatch</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerDispatch__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex Trigger Handler Name, full name</description>
    <label>ApexClass</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerDispatch__mdt/fields/SObjectName__c.field-meta.xml
<CustomField>
    <fullName>SObjectName__c</fullName>
    <description>SObject Name</description>
    <label>SObjectName</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerDispatchSelectorTest.cls
/**
 * TriggerDispatchSelectorTest
 */

@IsTest(IsParallel=false)
public class TriggerDispatchSelectorTest {

    public static void createDemoData() {
        TriggerDispatchSelector.OverwriteActiveTriggerDispatch = new List<TriggerDispatch__mdt>();
        TriggerDispatch__mdt item = new TriggerDispatch__mdt();
        item.ApexClass__c = DemoCaseTriggerHandler.class.getName();
        item.SObjectName__c = Case.class.getName();
        TriggerDispatchSelector.OverwriteActiveTriggerDispatch.add(item);
        TriggerDispatch__mdt item2 = new TriggerDispatch__mdt();
        item2.ApexClass__c = 'NeverFoundClass';
        item2.SObjectName__c = Case.class.getName();
        TriggerDispatchSelector.OverwriteActiveTriggerDispatch.add(item2);
    }

    @IsTest
    static void testBehavior() {
        TriggerDispatchSelector selector = new TriggerDispatchSelector();
        Test.startTest();
        createDemoData();
        List<TriggerDispatch__mdt> data = selector.getActiveTriggerDispatch();
        Test.stopTest();
        System.assertEquals(2, data.size());

    }

    @IsTest
    static void testBehavior2() {
        TriggerDispatchSelector selector = new TriggerDispatchSelector();
        Test.startTest();
        TriggerDispatchSelector.OverwriteActiveTriggerDispatch = null;
        List<TriggerDispatch__mdt> data = selector.getActiveTriggerDispatch();
        Test.stopTest();
        System.assert(data.size() >= 0);
    }
}