force-app/main/default/objects/TriggerDispatch__mdt/TriggerDispatch__mdt.object-meta.xml
<CustomObject>
    <description>Trigger Dispatcher</description>
    <label>TriggerDispatch</label>
    <pluralLabel>TriggerDispatch</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerDispatch__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>apex trigger is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerDispatch__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex Trigger Handler Name, full name</description>
    <label>ApexClass</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerDispatch__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Sort order of execution</description>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerDispatch__mdt/fields/SObjectName__c.field-meta.xml
<CustomField>
    <fullName>SObjectName__c</fullName>
    <description>SObject Name</description>
    <label>SObjectName</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerDispatchSelector.cls
/**
 * TriggerDispatchSelector
 */

global with sharing class TriggerDispatchSelector extends fflib_SObjectSelector{

    /**
    * Constructs the Selector
    *
    **/
    global TriggerDispatchSelector()
    {
        super(true, false, false);
    }

    /**
     * alternative result of methode
     */
    global static List<TriggerDispatch__mdt> OverwriteActiveTriggerDispatch { get; set;}

    public override List<SObjectField> getSObjectFieldList() {
        return new SObjectField[] {
                TriggerDispatch__mdt.Id,
                TriggerDispatch__mdt.Active__c,
                TriggerDispatch__mdt.ApexClass__c,
                TriggerDispatch__mdt.SObjectName__c,
                TriggerDispatch__mdt.Order__c
        };
    }


    public override SObjectType getSObjectType() {
        return TriggerDispatch__mdt.SObjectType;
    }

    global List<TriggerDispatch__mdt> getActiveTriggerDispatch() {
        this.ignoreCRUD();
        if (OverwriteActiveTriggerDispatch == null) {
            fflib_QueryFactory newquery = this.newQueryFactory();
            newquery.setCondition('Active__c = true ');
            newquery.getOrderings().clear();
            newquery.addOrdering('Order__c', fflib_QueryFactory.SortOrder.ASCENDING, false);
            return (List<TriggerDispatch__mdt>) Database.query(newquery.toSOQL());
        } else {
            return OverwriteActiveTriggerDispatch;
        }
    }
}